server:
  port: 8082

spring:
  application:
    name: loan-service
  cloud:
    function:
      definition: accountOpened;customerKycApproved
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        accountOpened-in-0:
          destination: account-opened
          group: loan-service
        customerKycApproved-in-0:
          destination: customer-kyc-approved
          group: loan-service
        loanDisbursed-out-0:
          destination: loan-disbursed

services:
  account-service:
    url: http://localhost:8081
  customer-service:
    url: http://localhost:8083
